# High Quality Configuration (TOML format)
# Configuration optimized for best quality results (longer training time)

[data]
n_data_points = 5000
noise_level = 0.15
random_state = 42

[model]
timesteps = 200
beta_min = 0.0001
beta_max = 0.02
hidden_dim = 512

[training]
n_epochs = 15000
learning_rate = 0.0005
batch_size = 256
scheduler_type = "cosine"
scheduler_eta_min = 0.000001

[visualization.general]
n_samples = 5000
n_trajectory_samples = 1000
create_visualizations = true

[visualization.gif]
create_gif = true
n_frames = 30
fps = 6
gif_type = "standard"

[visualization.progression]
create_progression_strip = true
frames = 8

[visualization.display]
figure_dpi = 300

[execution]
# Device to use for training: 'cpu', 'cuda', 'auto'
device = "auto"

# Verbose output (detailed information)
verbose = false

# Quiet output (minimal information)
quiet = false


[output]
# Save trained model
save_model = true

# Save final configuration
save_config = true

# Experiment name (for output files)
experiment_name = ""

# Output directory
output_dir = "outputs"
